PRODUCT_COPY_FILES += \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/mtk-ril.so:system/vendor/lib64/mtk-ril.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/librilmtk.so:system/vendor/lib64/librilmtk.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libaed.so:system/vendor/lib64/libaed.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libmrdump.so:system/vendor/lib64/libmrdump.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libmrdump.so:system/vendor/lib/libmrdump.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libaed.so:system/vendor/lib/libaed.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/librilmtk.so:system/vendor/lib/librilmtk.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libratconfig.so:system/vendor/lib64/libratconfig.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libratconfig.so:system/vendor/lib/libratconfig.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libmal.so:system/vendor/lib64/libmal.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libmdfx.so:system/vendor/lib64/libmdfx.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libmdfx.so:system/vendor/lib/libmdfx.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libmal.so:system/vendor/lib/libmal.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/mtk-ril.so:system/vendor/lib/mtk-ril.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/hw/camera.mt6737m.so:system/vendor/lib64/hw/camera.mt6737m.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libmtkcam_fwkutils.so:system/vendor/lib64/libmtkcam_fwkutils.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libmtkcam_fwkutils.so:system/vendor/lib/libmtkcam_fwkutils.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libcam_utils.so:system/vendor/lib64/libcam_utils.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libgralloc_extra.so:system/vendor/lib64/libgralloc_extra.so \
		vendor/Ulefone/S8_pro1/proprietary/lib64/libion.so:system/lib64/libion.so \
		vendor/Ulefone/S8_pro1/proprietary/lib/libion.so:system/lib/libion.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libion_mtk.so:system/vendor/lib64/libion_mtk.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libion_mtk.so:system/vendor/lib/libion_mtk.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libged.so:system/vendor/lib64/libged.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libged.so:system/vendor/lib/libged.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libgralloc_extra.so:system/vendor/lib/libgralloc_extra.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libmtk_mmutils.so:system/vendor/lib64/libmtk_mmutils.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libmtk_mmutils.so:system/vendor/lib/libmtk_mmutils.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libcam_platform.so:system/vendor/lib64/libcam_platform.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libcamdrv.so:system/vendor/lib64/libcamdrv.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libm4u.so:system/vendor/lib64/libm4u.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libm4u.so:system/vendor/lib/libm4u.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libbwc.so:system/vendor/lib64/libbwc.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libbwc.so:system/vendor/lib/libbwc.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libcamdrv.so:system/vendor/lib/libcamdrv.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libcam.device1.so:system/vendor/lib64/libcam.device1.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libcam_mmp.so:system/vendor/lib64/libcam_mmp.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libcam_mmp.so:system/vendor/lib/libcam_mmp.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libcam_hwutils.so:system/vendor/lib64/libcam_hwutils.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libcam_hwutils.so:system/vendor/lib/libcam_hwutils.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libcam.utils.so:system/vendor/lib64/libcam.utils.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libcam.utils.so:system/vendor/lib/libcam.utils.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libcam1_utils.so:system/vendor/lib64/libcam1_utils.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libcam1_utils.so:system/vendor/lib/libcam1_utils.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libcam.paramsmgr.so:system/vendor/lib64/libcam.paramsmgr.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libcam.halsensor.so:system/vendor/lib64/libcam.halsensor.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libcameracustom.so:system/vendor/lib64/libcameracustom.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libcameracustom.so:system/vendor/lib/libcameracustom.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libcam.metadata.so:system/vendor/lib64/libcam.metadata.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libcam.metadata.so:system/vendor/lib/libcam.metadata.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libcam.halsensor.so:system/vendor/lib/libcam.halsensor.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libfeatureio.so:system/vendor/lib64/libfeatureio.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libcam.utils.sensorlistener.so:system/vendor/lib64/libcam.utils.sensorlistener.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libcam.utils.sensorlistener.so:system/vendor/lib/libcam.utils.sensorlistener.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libcamdrv_FrmB.so:system/vendor/lib64/libcamdrv_FrmB.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libcamdrv_FrmB.so:system/vendor/lib/libcamdrv_FrmB.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libcamalgo.so:system/vendor/lib64/libcamalgo.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libmtk_drvb.so:system/vendor/lib64/libmtk_drvb.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libmtk_drvb.so:system/vendor/lib/libmtk_drvb.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libperfservicenative.so:system/vendor/lib64/libperfservicenative.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libperfservice.so:system/vendor/lib64/libperfservice.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libtouchfilter.so:system/vendor/lib64/libtouchfilter.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libtouchfilter.so:system/vendor/lib/libtouchfilter.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libperfservice.so:system/vendor/lib/libperfservice.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libperfservicenative.so:system/vendor/lib/libperfservicenative.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libcamalgo.so:system/vendor/lib/libcamalgo.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libfeatureiodrv.so:system/vendor/lib64/libfeatureiodrv.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libcam.iopipe_FrmB.so:system/vendor/lib64/libcam.iopipe_FrmB.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libimageio_plat_drv_FrmB.so:system/vendor/lib64/libimageio_plat_drv_FrmB.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libdpframework.so:system/vendor/lib64/libdpframework.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libpqservice.so:system/vendor/lib64/libpqservice.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libpq_prot.so:system/vendor/lib64/libpq_prot.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libpq_cust.so:system/vendor/lib64/libpq_cust.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libpq_cust.so:system/vendor/lib/libpq_cust.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libpq_prot.so:system/vendor/lib/libpq_prot.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libpqservice.so:system/vendor/lib/libpqservice.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libvcodecdrv.so:system/vendor/lib64/libvcodecdrv.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libvcodec_utility.so:system/vendor/lib64/libvcodec_utility.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libvcodec_utility.so:system/vendor/lib/libvcodec_utility.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libmp4enc_xa.ca7.so:system/vendor/lib/libmp4enc_xa.ca7.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libvcodec_oal.so:system/vendor/lib64/libvcodec_oal.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libvcodec_oal.so:system/vendor/lib/libvcodec_oal.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libmp4enc_sa.ca7.so:system/vendor/lib/libmp4enc_sa.ca7.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libh264enc_sb.ca7.so:system/vendor/lib/libh264enc_sb.ca7.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libh264enc_sa.ca7.so:system/vendor/lib64/libh264enc_sa.ca7.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libh264enc_sa.ca7.so:system/vendor/lib/libh264enc_sa.ca7.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libvp8enc_sa.ca7.so:system/vendor/lib/libvp8enc_sa.ca7.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libvp8dec_sa.ca7.so:system/vendor/lib/libvp8dec_sa.ca7.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libvp9dec_sa.ca7.so:system/vendor/lib/libvp9dec_sa.ca7.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libvc1dec_sa.ca7.so:system/vendor/lib/libvc1dec_sa.ca7.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libvcodecdrv.so:system/vendor/lib/libvcodecdrv.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libuvtswenc_sa.ca7.android.so:system/vendor/lib/libuvtswenc_sa.ca7.android.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libHEVCdec_sa.ca7.android.so:system/vendor/lib/libHEVCdec_sa.ca7.android.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/liblic_divx.so:system/vendor/lib/liblic_divx.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/liblic_s263.so:system/vendor/lib/liblic_s263.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libdpframework.so:system/vendor/lib/libdpframework.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libimageio_plat_drv_FrmB.so:system/vendor/lib/libimageio_plat_drv_FrmB.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libimageio_FrmB.so:system/vendor/lib64/libimageio_FrmB.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libimageio_FrmB.so:system/vendor/lib/libimageio_FrmB.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libcam.iopipe_FrmB.so:system/vendor/lib/libcam.iopipe_FrmB.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libnvramagentclient.so:system/vendor/lib64/libnvramagentclient.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libnvram.so:system/vendor/lib64/libnvram.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libcustom_nvram.so:system/vendor/lib64/libcustom_nvram.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libcustom_nvram.so:system/vendor/lib/libcustom_nvram.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libnvram_platform.so:system/vendor/lib64/libnvram_platform.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libnvram_platform.so:system/vendor/lib/libnvram_platform.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libnvram_sec.so:system/vendor/lib64/libnvram_sec.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libnvram_sec.so:system/vendor/lib/libnvram_sec.so \
		vendor/Ulefone/S8_pro1/proprietary/lib64/libfs_mgr.so:system/lib64/libfs_mgr.so \
		vendor/Ulefone/S8_pro1/proprietary/lib/libfs_mgr.so:system/lib/libfs_mgr.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libnvram.so:system/vendor/lib/libnvram.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libnvramagentclient.so:system/vendor/lib/libnvramagentclient.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libfeatureiodrv.so:system/vendor/lib/libfeatureiodrv.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libcam.iopipe.so:system/vendor/lib64/libcam.iopipe.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libJpgEncPipe.so:system/vendor/lib64/libJpgEncPipe.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libmtkjpeg.so:system/vendor/lib64/libmtkjpeg.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libmtkjpeg.so:system/vendor/lib/libmtkjpeg.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libJpgEncPipe.so:system/vendor/lib/libJpgEncPipe.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libcam.iopipe.so:system/vendor/lib/libcam.iopipe.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/lib3a.so:system/vendor/lib64/lib3a.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/lib3a.so:system/vendor/lib/lib3a.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libcam.exif.so:system/vendor/lib64/libcam.exif.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libcam.exif.so:system/vendor/lib/libcam.exif.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libfeatureio.so:system/vendor/lib/libfeatureio.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libcam.paramsmgr.so:system/vendor/lib/libcam.paramsmgr.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libcam.client.so:system/vendor/lib64/libcam.client.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libcam.client.so:system/vendor/lib/libcam.client.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libcam.camadapter.so:system/vendor/lib64/libcam.camadapter.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libimageio.so:system/vendor/lib64/libimageio.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libimageio_plat_drv.so:system/vendor/lib64/libimageio_plat_drv.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libimageio_plat_drv.so:system/vendor/lib/libimageio_plat_drv.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libimageio.so:system/vendor/lib/libimageio.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libcam.campipe.so:system/vendor/lib64/libcam.campipe.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libcam.campipe.so:system/vendor/lib/libcam.campipe.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libcam.camshot.so:system/vendor/lib64/libcam.camshot.so \
		vendor/Ulefone/S8_pro1/proprietary/lib64/libgybeauty.so:system/lib64/libgybeauty.so \
		vendor/Ulefone/S8_pro1/proprietary/lib64/libgybeauty422.so:system/lib64/libgybeauty422.so \
		vendor/Ulefone/S8_pro1/proprietary/lib64/libgybeauty420.so:system/lib64/libgybeauty420.so \
		vendor/Ulefone/S8_pro1/proprietary/lib/libgybeauty420.so:system/lib/libgybeauty420.so \
		vendor/Ulefone/S8_pro1/proprietary/lib/libgybeauty422.so:system/lib/libgybeauty422.so \
		vendor/Ulefone/S8_pro1/proprietary/lib/libgybeauty.so:system/lib/libgybeauty.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libBlurModoule.so:system/vendor/lib64/libBlurModoule.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libBlurModoule.so:system/vendor/lib/libBlurModoule.so \
		vendor/Ulefone/S8_pro1/proprietary/lib64/libBlurModoule.so:system/lib64/libBlurModoule.so \
		vendor/Ulefone/S8_pro1/proprietary/lib/libBlurModoule.so:system/lib/libBlurModoule.so \
		vendor/Ulefone/S8_pro1/proprietary/lib64/libfn.vsfb.so:system/lib64/libfn.vsfb.so \
		vendor/Ulefone/S8_pro1/proprietary/lib64/libFNVfbEngineHAL.so:system/lib64/libFNVfbEngineHAL.so \
		vendor/Ulefone/S8_pro1/proprietary/lib/libFNVfbEngineHAL.so:system/lib/libFNVfbEngineHAL.so \
		vendor/Ulefone/S8_pro1/proprietary/lib/libfn.vsfb.so:system/lib/libfn.vsfb.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libcam.camshot.so:system/vendor/lib/libcam.camshot.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libcam.camadapter.so:system/vendor/lib/libcam.camadapter.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libcam.device1.so:system/vendor/lib/libcam.device1.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libcam.device3.so:system/vendor/lib64/libcam.device3.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libcam.metadataprovider.so:system/vendor/lib64/libcam.metadataprovider.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libcam.hal3a.v3.dng.so:system/vendor/lib64/libcam.hal3a.v3.dng.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libcam.hal3a.v3.dng.so:system/vendor/lib/libcam.hal3a.v3.dng.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libcam.metadataprovider.so:system/vendor/lib/libcam.metadataprovider.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libcam3_app.so:system/vendor/lib64/libcam3_app.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libcam3_utils.so:system/vendor/lib64/libcam3_utils.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libcam3_utils.so:system/vendor/lib/libcam3_utils.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libcam3_app.so:system/vendor/lib/libcam3_app.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libcam3_pipeline.so:system/vendor/lib64/libcam3_pipeline.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libcam3_pipeline.so:system/vendor/lib/libcam3_pipeline.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libcam3_hwpipeline.so:system/vendor/lib64/libcam3_hwpipeline.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libcam3_hwnode.so:system/vendor/lib64/libcam3_hwnode.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libcam.hal3a.v3.so:system/vendor/lib64/libcam.hal3a.v3.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libcam.hal3a.v3.so:system/vendor/lib/libcam.hal3a.v3.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libcam.exif.v3.so:system/vendor/lib64/libcam.exif.v3.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libcam.exif.v3.so:system/vendor/lib/libcam.exif.v3.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libhdrproc.so:system/vendor/lib64/libhdrproc.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libhdrproc.so:system/vendor/lib/libhdrproc.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libcam3_hwnode.so:system/vendor/lib/libcam3_hwnode.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libcam3_hwpipeline.so:system/vendor/lib/libcam3_hwpipeline.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libcam.device3.so:system/vendor/lib/libcam.device3.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libcam_platform.so:system/vendor/lib/libcam_platform.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libcam_utils.so:system/vendor/lib/libcam_utils.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/hw/camera.mt6737m.so:system/vendor/lib/hw/camera.mt6737m.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/hw/audio.usb.mt6737m.so:system/vendor/lib64/hw/audio.usb.mt6737m.so \
		vendor/Ulefone/S8_pro1/proprietary/lib64/libalsautils.so:system/lib64/libalsautils.so \
		vendor/Ulefone/S8_pro1/proprietary/lib/libalsautils.so:system/lib/libalsautils.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/hw/audio.usb.mt6737m.so:system/vendor/lib/hw/audio.usb.mt6737m.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/hw/audio.r_submix.mt6737m.so:system/vendor/lib64/hw/audio.r_submix.mt6737m.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/hw/audio.r_submix.mt6737m.so:system/vendor/lib/hw/audio.r_submix.mt6737m.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/bin/MtkCodecService:system/vendor/bin/MtkCodecService \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib64/libBnMtkCodec.so:system/vendor/lib64/libBnMtkCodec.so \
		vendor/Ulefone/S8_pro1/proprietary/vendor/lib/libBnMtkCodec.so:system/vendor/lib/libBnMtkCodec.so
